name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn -B package --file pom.xml

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Test with Maven
        run: mvn -B test

  sonarcloud-analysis:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: SonarCloud analysis
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.projectKey=${{ secrets.SONAR_PROJECTKEY }} \
          -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.token=${{ secrets.SONAR_TOKEN }}

      - name: Install xmllint
        run: sudo apt-get install -y libxml2-utils

      - name: Check JaCoCo Coverage
        run: |
          JACOCO_XML_PATH=target/site/jacoco/jacoco.xml
          if [ ! -f "$JACOCO_XML_PATH" ]; then
            echo "JaCoCo report not found!"
            exit 1
          fi
          
          COVERAGE=$(xmllint --xpath 'string(//report/counter[@type="INSTRUCTION"]/@covered)' $JACOCO_XML_PATH)
          MISSED=$(xmllint --xpath 'string(//report/counter[@type="INSTRUCTION"]/@missed)' $JACOCO_XML_PATH)
          
          TOTAL=$((COVERAGE + MISSED))
          
          if [ "$TOTAL" -eq 0 ]; then
            echo "Error: Total instructions count is zero, cannot calculate coverage."
            exit 1
          fi

          PERCENTAGE=$(echo "scale=2; $COVERAGE / $TOTAL * 70" | bc)
          echo "Code coverage percentage: $PERCENTAGE%"

          if (( $(echo "$PERCENTAGE < 50" | bc -l) )); then
            echo "Code coverage is below 50%: $PERCENTAGE%"
            exit 1
          fi

  deploy-to-dockerhub:
    needs: sonarcloud-analysis
    runs-on: ubuntu-latest


